# -*- coding: utf-8 -*-
"""Elon_face_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cOO-M4Fyx5HYwOZLc4bVA1yPThafdmEl
"""

# Commented out IPython magic to ensure Python compatibility.
#face recognition api
#!pip install face_recognition
# %cd face_recognition

"""# Project: Elon Musk Face Detection"""

import face_recognition
import numpy as np
from google.colab.patches import cv2_imshow
import cv2

"""Create Encoding Profile using known faces images"""

elon_face = face_recognition.load_image_file("elon.jpg")
elon_face_encoding = face_recognition.face_encodings(elon_face)[0]

known_face_encodings = [ elon_face_encoding ]
known_face_names = [ "Elon Musk" ]

"""Run face recognition on unknown faces"""

file_name = "unknown_el.jpg"
unknown_image = face_recognition.load_image_file(file_name)
unknown_image_to_draw = cv2.imread(file_name)
face_locations = face_recognition.face_locations(unknown_image)
face_encodings = face_recognition.face_encodings(unknown_image, face_locations)

for(top,right, bottom, left), face_encodings in zip(face_locations, face_encodings):
  matches = face_recognition.compare_faces(known_face_encodings, face_encodings)
  name = "Unknown"
  face_distances = face_recognition.face_distance(known_face_encodings, face_encodings)
  best_match_index = np.argmin(face_distances)
  if matches[best_match_index]:
    name = known_face_names[best_match_index]
  cv2.rectangle(unknown_image_to_draw, (left, top), (right,bottom), (0,255,0), 3)
  cv2.putText(unknown_image_to_draw, name, (left, top-20), cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2, cv2.LINE_AA)
cv2_imshow(unknown_image_to_draw)